apiVersion: v1

kind: Pod

metadata:
  name: new-ethadapter
  labels:
    app: new-ethadapter

spec:
  containers:
    - name: new-ethadapter-container
      image: pharmaledger/apiadapter:latest
      env:
        - name: RPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: new-eth-adapter-config
              key: RPC_ADDRESS
        - name: SMARTCONTRACTADDRESS
          valueFrom:
            configMapKeyRef:
              name: new-eth-adapter-config
              key: SMARTCONTRACTADDRESS
        - name: SMARTCONTRACTABI
          valueFrom:
            configMapKeyRef:
              key: SMARTCONTRACTABI
              name: new-eth-adapter-config
        - name: ORGACCOUNT
          valueFrom:
            configMapKeyRef:
              key: ORGACCOUNT
              name: new-eth-adapter-config
      ports:
        - containerPort: 3000
      imagePullPolicy: Always


---


apiVersion: v1
kind: Service
metadata:
  name: new-ethadapter-service
  labels:
    name: new-ethadapter-service

spec:
  selector:
    app: new-ethadapter

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer


