apiVersion: v1

kind: Pod

metadata:
  name: new-anchorsmart
  labels:
    app: new-anchorsmart

spec:
  restartPolicy: "Always"
  containers:
    - name: new-anchorsmart-container
      image: pharmaledger/anchor_smart:latest
      imagePullPolicy: Always
      env:
      # API endpoint to obtain abi and smart contract address by reading the value of 'contractAddress' or 'abi' from the returned json
      # GET /contractAddress
      # GET /abi
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: new-anchor-configmap
              key: PORT
        - name: ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: new-anchor-configmap
              key: ACCOUNT
        - name: RPC_HOST
          valueFrom:
            configMapKeyRef:
              name: new-anchor-configmap
              key: RPC_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: new-anchorsmart-service
  labels:
    name: new-anchorsmart-service

spec:
  selector:
    app: new-anchorsmart

  ports:
    - port: 5000
      targetPort: 5000

  type: ClusterIP